; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; Build src filter is used to specify which files to include in the build process for this environment
; cmd to push specific env to a board: 
; open pio terminal and run:
; pio run -e <env_name> --target upload

[env] ; common environment settings 
platform = atmelavr ;chip architecture
board = uno
framework = arduino
monitor_speed = 9600
build_flags = -Wall -Wextra ; enables warnings and extra warnings

[env:sensor_node]
build_src_filter = +<common/> +<sensor_node/>

[env:relay_node]
build_src_filter = +<common/> +<relay_node_node/>

