; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; Build src filter is used to specify which files to include in the build process for this environment

[env]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
build_flags = -Wall -Wextra ; enables warnings and extra warnings

[env:sensor_node]
build_src_filter = +<common/> +<sensor_node/>
upload_port = COM4

[env:display_node]
build_src_filter = +<common/> +<display_node/>
upload_port = COM3
